# Generated by Django 3.0.3 on 2020-05-05 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20200506_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('OrderID', models.IntegerField(auto_created=True, default=1, editable=False, primary_key=True, serialize=False, verbose_name='订单编号')),
                ('menu', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=10)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='login.student')),
            ],
        ),
    ]
