# Generated by Django 3.0.3 on 2020-05-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
