# Generated by Django 3.0.3 on 2020-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time',
            new_name='delivery_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderID',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='订单编号'),
        ),
    ]
