# Generated by Django 3.0.3 on 2020-05-05 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200506_0033'),
        ('diancan', '0003_auto_20200506_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(max_length=10, verbose_name='配送时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.CharField(max_length=1000, verbose_name='订购菜品'),
        ),
        migrations.AlterField(
            model_name='order',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='login.student', verbose_name='学生学号'),
        ),
    ]
