# Generated by Django 3.0.3 on 2020-05-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0004_auto_20200506_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='heyi',
            fields=[
                ('menu_ID', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='菜品')),
                ('name', models.CharField(max_length=20, verbose_name='菜品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='菜品价格')),
                ('windows_name', models.CharField(max_length=30, verbose_name='窗口名称')),
                ('image', models.ImageField(upload_to='media/image/heyi', verbose_name='菜品照片')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='xinbei',
            fields=[
                ('menu_ID', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='菜品')),
                ('name', models.CharField(max_length=20, verbose_name='菜品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='菜品价格')),
                ('windows_name', models.CharField(max_length=30, verbose_name='窗口名称')),
                ('image', models.ImageField(upload_to='media/image/xinbei', verbose_name='菜品照片')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='xuer',
            fields=[
                ('menu_ID', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='菜品')),
                ('name', models.CharField(max_length=20, verbose_name='菜品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='菜品价格')),
                ('windows_name', models.CharField(max_length=30, verbose_name='窗口名称')),
                ('image', models.ImageField(upload_to='media/image/xuer', verbose_name='菜品照片')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
