# Generated by Django 3.0.3 on 2020-05-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0005_heyi_xinbei_xuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(default=7, max_length=2, verbose_name='送货地点'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='金雄', max_length=20, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='telephone_num',
            field=models.CharField(default=18813081247, max_length=11, verbose_name='电话号码'),
            preserve_default=False,
        ),
    ]
