# Generated by Django 3.0.3 on 2020-05-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0006_auto_20200506_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='heyi',
            name='for_sale',
            field=models.BooleanField(default=1, verbose_name='是否出售'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heyi',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次编辑'),
        ),
        migrations.AddField(
            model_name='xinbei',
            name='for_sale',
            field=models.BooleanField(default=1, verbose_name='是否出售'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xinbei',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次编辑'),
        ),
        migrations.AddField(
            model_name='xuer',
            name='for_sale',
            field=models.BooleanField(default=1, verbose_name='是否出售'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xuer',
            name='last_edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后一次编辑'),
        ),
    ]
