# Generated by Django 2.2.2 on 2020-05-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0009_auto_20200508_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='dish_ID',
            field=models.IntegerField(default=1, verbose_name='菜品序号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishes',
            name='windows_name',
            field=models.CharField(default=1, max_length=20, verbose_name='定菜窗口'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heyi',
            name='menu_ID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='菜品'),
        ),
        migrations.AlterField(
            model_name='xuer',
            name='menu_ID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='菜品'),
        ),
    ]
