# Generated by Django 2.2.2 on 2020-05-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0010_auto_20200508_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xinbei',
            name='menu_ID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='菜品'),
        ),
    ]
