# Generated by Django 2.2.2 on 2020-05-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0012_comment_grade_choice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'OrderID', 'verbose_name': '全部订单', 'verbose_name_plural': '全部订单'},
        ),
        migrations.AlterField(
            model_name='order',
            name='OrderID',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='订单编号'),
        ),
    ]
