# Generated by Django 3.0.5 on 2020-05-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0014_auto_20200511_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_username',
            field=models.CharField(default='匿名用户', max_length=30),
        ),
    ]
