# Generated by Django 2.2.4 on 2020-05-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diancan', '0015_comment_comment_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heyi',
            name='image_source',
        ),
        migrations.RemoveField(
            model_name='xinbei',
            name='image_source',
        ),
        migrations.RemoveField(
            model_name='xuer',
            name='image_source',
        ),
    ]
