# Generated by Django 2.2.4 on 2020-04-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sno', models.CharField(max_length=8)),
                ('tele', models.CharField(max_length=11)),
                ('dnum', models.CharField(max_length=2)),
            ],
        ),
    ]
