# Generated by Django 3.0.3 on 2020-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_student_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=100, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dnum',
            field=models.CharField(max_length=2, verbose_name='公寓位置'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sno',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tele',
            field=models.CharField(max_length=11, verbose_name='电话号码'),
        ),
    ]
