# Generated by Django 2.2.2 on 2020-05-06 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200506_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '注册用户信息', 'verbose_name_plural': '注册用户信息'},
        ),
    ]
