# Generated by Django 2.2.2 on 2020-05-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20200506_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='deliveryman',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='外卖员编号')),
                ('name', models.CharField(max_length=30, verbose_name='姓名')),
                ('telephone', models.IntegerField(verbose_name='电话号码')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='外卖员工资')),
                ('last_login', models.DateTimeField(verbose_name='上次登录时间')),
                ('code', models.CharField(max_length=100, verbose_name='密码')),
                ('seniority', models.IntegerField(verbose_name='工龄')),
            ],
        ),
        migrations.RemoveField(
            model_name='student_contact',
            name='telephone_num',
        ),
        migrations.AddField(
            model_name='student_contact',
            name='telephone',
            field=models.IntegerField(default=1, verbose_name='电话号码'),
            preserve_default=False,
        ),
    ]
