# Generated by Django 2.2.2 on 2020-05-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200509_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='userID',
            field=models.IntegerField(auto_created=True, default=1, verbose_name='用户名称'),
            preserve_default=False,
        ),
    ]
